### ISSUE TITLE
ValueError: Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.

### ISSUE THREAD

**Issue by synalice** [burenotti/runbox#2]
1. I copy example code from README
2. I install all dependencies
3. I run it
4. I get an error message: `ValueError: Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.`

Full error message:
```
Traceback (most recent call last):
  File "/home/synalice/Coding/Tests/main.py", line 55, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/synalice/Coding/Tests/main.py", line 29, in main
    executor = runbox.DockerExecutor()
  File "/home/synalice/Coding/Tests/venv/lib/python3.10/site-packages/runbox/docker/docker_api.py", line 28, in __init__
    self.docker_client = docker_client or Docker(url)
  File "/home/synalice/Coding/Tests/venv/lib/python3.10/site-packages/aiodocker/docker.py", line 99, in __init__
    raise ValueError(
ValueError: Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.

Process finished with exit code 1
```

I do have docker installed: 
```
$ docker --version
Docker version 20.10.14, build a224086349
```

**Comment by synalice** [comment]
All I had to do is to enable docker daemon:
```
$ sudo systemctl enable docker
$ sudo systemctl start docker
```
